import type { Mission } from "@/types/game";

export const awsMissions: Mission[] = [
  {
    id: "aws-learn",
    stationId: "aws",
    mode: "learn",
    title: "LAMP on a cloud VM",
    summary: "Preview how the same stack maps onto AWS.",
    xp: 50,
    requires: ["lamp-diy"],
    steps: [{ id: "aws-learn-1", type: "read", lessonId: "aws-preview" }],
  },
  {
    id: "aws-practice",
    stationId: "aws",
    mode: "practice",
    title: "Configure EC2 instance",
    summary: "Simulate launching and configuring an EC2 instance.",
    xp: 75,
    requires: ["aws-learn"],
    steps: [
      {
        id: "aws-practice-quiz",
        type: "quiz",
        question: "Which AWS service provides virtual machines?",
        choices: ["S3 bucket", "EC2 instance", "CloudFront", "Route 53 only"],
        answer: 1,
        hint: "Think virtual machines.",
      },
      {
        id: "aws-practice-ssh",
        type: "command",
        shell: "bash",
        prompt: "Simulate SSH into your EC2 instance.",
        expect: { kind: "includes", value: "ssh" },
        hint: "Use: ssh ubuntu@your-instance-ip",
      },
      {
        id: "aws-practice-deploy",
        type: "command",
        shell: "bash",
        prompt: "Update packages on the instance.",
        expect: { kind: "includes", value: "apt update" },
        hint: "Use: sudo apt update",
      },
    ],
  },
  {
    id: "aws-diy",
    stationId: "aws",
    mode: "diy",
    title: "Complete cloud deployment",
    summary: "Simulate the full LAMP deployment on AWS.",
    xp: 100,
    requires: ["aws-practice"],
    steps: [
      {
        id: "aws-diy-install",
        type: "command",
        shell: "bash",
        prompt: "Install Apache on the EC2 instance.",
        expect: { kind: "includes", value: "apt install apache2" },
        hint: "Use: sudo apt install apache2",
      },
      {
        id: "aws-diy-start",
        type: "command",
        shell: "bash",
        prompt: "Start Apache on the instance.",
        expect: { kind: "includes", value: "systemctl start apache2" },
        hint: "Use: sudo systemctl start apache2",
      },
      {
        id: "aws-diy-checklist",
        type: "checklist",
        items: [
          "Security group allows port 22 (SSH) from my IP.",
          "Security group allows port 80 (HTTP) from 0.0.0.0/0.",
          "Apache is running and accessible via public IP.",
          "I understand the difference between local and cloud deployment.",
        ],
        hint: "These are the key steps for deploying LAMP on AWS EC2.",
      },
    ],
  },
];
