import type { Mission } from "@/types/game";

export const lampMissions: Mission[] = [
  {
    id: "lamp-learn",
    stationId: "lamp",
    mode: "learn",
    title: "Trace one request",
    summary: "See Linux, Apache, MySQL, and PHP in a single path.",
    xp: 50,
    requires: ["linux-diy", "apache-diy", "php-diy", "mysql-diy"],
    steps: [{ id: "lamp-learn-1", type: "read", lessonId: "lamp-together" }],
  },
  {
    id: "lamp-practice",
    stationId: "lamp",
    mode: "practice",
    title: "Name each hop",
    summary: "Identify which component handles which job.",
    xp: 75,
    requires: ["lamp-learn"],
    steps: [
      {
        id: "lamp-practice-trace",
        type: "command",
        shell: "lamp",
        prompt: "Type the request path acronym in order (hint: start with L).",
        expect: { kind: "includes", value: "lamp" },
        hint: "Linux, Apache, MySQL, PHP — but the path is often Linux → Apache → PHP → MySQL. Type lamp to confirm the stack name.",
      },
      {
        id: "lamp-practice-quiz",
        type: "quiz",
        question: "A browser requests /index.php. What runs the PHP file?",
        choices: [
          "MySQL executes it as SQL",
          "Apache hands it to PHP, then returns HTML",
          "Linux compiles it to a kernel module",
          "The browser's JavaScript engine",
        ],
        answer: 1,
        hint: "Apache is the front door; PHP is the worker.",
      },
    ],
  },
  {
    id: "lamp-diy",
    stationId: "lamp",
    mode: "diy",
    title: "Stack health check",
    summary: "Confirm you can explain a full LAMP round trip.",
    xp: 100,
    requires: ["lamp-practice"],
    steps: [
      {
        id: "lamp-diy-health",
        type: "command",
        shell: "lamp",
        prompt: "Run the stack health check.",
        expect: { kind: "includes", value: "health" },
        hint: "Type health",
      },
      {
        id: "lamp-diy-checklist",
        type: "checklist",
        items: [
          "I can explain Linux → Apache → PHP → MySQL → HTML response.",
          "I am ready to think about deploying this stack on a cloud VM.",
        ],
        hint: "This unlocks the AWS preview station.",
      },
    ],
  },
  {
    id: "lamp-final",
    stationId: "lamp",
    mode: "diy",
    title: "Final Challenge: Deploy LAMP",
    summary: "You have a fresh Ubuntu server. Deploy a complete LAMP stack.",
    xp: 200,
    requires: ["aws-diy"],
    steps: [
      {
        id: "lamp-final-update",
        type: "command",
        shell: "bash",
        prompt: "Update the package list on your fresh server.",
        expect: { kind: "includes", value: "apt update" },
        hint: "Start with: sudo apt update",
      },
      {
        id: "lamp-final-apache",
        type: "command",
        shell: "bash",
        prompt: "Install Apache web server.",
        expect: { kind: "includes", value: "apt install apache2" },
        hint: "Install Apache: sudo apt install apache2",
      },
      {
        id: "lamp-final-apache-start",
        type: "command",
        shell: "bash",
        prompt: "Start the Apache service.",
        expect: { kind: "includes", value: "systemctl start apache2" },
        hint: "Start Apache: sudo systemctl start apache2",
      },
      {
        id: "lamp-final-php",
        type: "command",
        shell: "bash",
        prompt: "Install PHP and the Apache PHP module.",
        expect: { kind: "includes", value: "apt install php" },
        hint: "Install PHP: sudo apt install php libapache2-mod-php",
      },
      {
        id: "lamp-final-mysql",
        type: "command",
        shell: "bash",
        prompt: "Install MySQL database server.",
        expect: { kind: "includes", value: "apt install mysql-server" },
        hint: "Install MySQL: sudo apt install mysql-server",
      },
      {
        id: "lamp-final-check",
        type: "command",
        shell: "lamp",
        prompt: "Verify your LAMP stack health.",
        expect: { kind: "includes", value: "health" },
        hint: "Check stack health: health",
      },
      {
        id: "lamp-final-checklist",
        type: "checklist",
        items: [
          "I installed and started Apache on Linux.",
          "I installed PHP with Apache integration.",
          "I installed MySQL for data storage.",
          "I understand how requests flow through the complete stack.",
          "I am ready to deploy real applications on LAMP.",
        ],
        hint: "You have mastered the fundamentals of the LAMP stack!",
      },
    ],
  },
];
